### ISSUE TITLE
Can you please add GitLab support?

### ISSUE THREAD

**Issue by unphased** [laurent22/github-actions-logs-extension#1]
enable also on these URLs: `https://cdn.artifacts.gitlab-static.net/*`

**Comment by laurent22** [comment]
Sure, but are you sure it would work with GitLab too? Since I've only tested with GitHub and they may have a specific format

**Comment by unphased** [comment]
from a cursory glance... I feel like it would work at least to get the colors in. Both systems should just be emitting a raw log including raw ansi escapes so I see no reason why it wouldn't just work. In GitLab the individual commands are collapsible (and this extension does handle that: https://chrome.google.com/webstore/detail/gitlab-ci-logs-viewer/mjjniaplbhdjmhkmfknkbemfjghofaff?hl=en and I'm currently using it) but I just think adding that as another valid URL prefix would be great. The other extension does not have a narrow url filter, which is nice to have. If I have time I can try this myself too.

**Comment by laurent22** [comment]
Ok I've uploaded a new version (1.1.2) with support for GitLab, so please let me know if it works for you. It should be in the store in a day or two
